### ISSUE TITLE
simple transposes?

### ISSUE THREAD

**Issue by chichilalescu** [hgomersall/pyFFTW#57]
Hello,

Thanks for the great package. Using it right now for huge chunks of data, it's working beautifully.
I have a small question: how hard is it to expand your FFTW class for the case of simple transposes?
I found this http://agentzlerich.blogspot.com/2010/01/using-fftw-for-in-place-matrix.html a couple of weeks ago, and I adapted it for my needs in an MPI code (see lines 384 and 414 of https://github.com/idies/MPIArrayTools/blob/master/src/field_descriptor.cpp if you're interested).

However, it turns out I'm gonna use your python wrapper for my big job in the end, and I was curious if the same functionality could be added to pyFFTW. I have zero experience with .pyx files however... So, could you please let me know if the extension is hard? if not, do you have some hints on what I need to do?

Thanks,
Chichi L

**Comment by hgomersall** [comment]
Do you mean arbitrary ordering of axes in memory? If so, it already supports this. Essentially, pyFFTW can work with any valid numpy array without a copy (at least, this is true if you use the FFTW class directly, or suitable arguments to the builders interface). If not, please clarify as I no longer understand!

Numpy defines the layout in memory in terms of strides and item sizes along each axes, and strides don't need to monotonically change for increasing or decreasing axis (you can have e.g. middle major ordering in a three axis array). A 2D transpose is the trivial case in which the strides are swapped.

Note, however, that you may get a faster transform by copying the array if you can cope with that. This is due to speed ups in the memory loads due to alignment as well as simply have better spatial locality of reference. Having a play and see is the best route to working this out (timeit is your friend here).

Also, just for the record, MPI is not supported.

Cheers.

**Comment by hgomersall** [comment]
Just to add to the last post, the method you use is to do the transpose in numpy, which will not perform a copy, then you simply take the FFT of that array. You should be able to transpose both the input and the output array.

**Comment by chichilalescu** [comment]
Thank you, that was all that I needed. I just had gotten it in my mind that I needed to transpose the data since I first wrote this code using MPI, where the layout is set in stone. However, a view works just fine.
