### ISSUE TITLE
is python 3.5 supported?

### ISSUE THREAD

**Issue by crocha700** [hgomersall/pyFFTW#71]
I get the following when trying to install `pyfftw` with `conda` on [comet XSDE](https://portal.xsede.org/sdsc-comet):

```{bash}
[cbrocha@comet-ln2 pyqg]$ conda install -c https://conda.anaconda.org/jakirkham pyfftw
Fetching package metadata: ......
Solving package specifications: .........
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|###################################################| 100%


Hint: the following packages conflict with each other:
  - pyfftw
  - python 3.5*
```

**Comment by hgomersall** [comment]
Hmmm, it builds and completes just fine with the windows Appveyor build with 3.5 (which is more than can be said for some of the other versions, and is the only one I've tested).

I'd expect it to work and can think of no reason why it would not. I suggest the problem is something in the way anaconda packages things...? https://conda.anaconda.org/jakirkham looks like a third party repository?

**Comment by hgomersall** [comment]
To confirm, it is supported on both Linux and Windows. The CI tests are run as such.
